---
- hosts: all
  sudo: true
  vars_prompt:
  - name: "xroad_superuser_password"
    prompt: "Please enter password for X-Road superuser"
    private: yes
    encrypt: "sha512_crypt"
    confirm: yes
  roles:
    - role: forge_ssl
    - { role: kapa-secureserver,
        xroad_admin_fqdn: "{{ inventory_hostname }}",
        xroad_service_fqdn: "{{ xroad_admin_fqdn }}",
        nginx_ssl_cert: "/etc/ssl/forgeservicelab.fi.key",
        nginx_ssl_key: "/etc/ssl/forgeservicelab.fi.crt" }
